### PR TITLE
Upgrade to GPflow 2

### PR DESCRIPTION
**Pull request by st--**
This PR upgrades the code to run under current versions of GPflow & TensorFlow (tested with gpflow 2.5 and tensorflow 2.5).
Note that I could not test out the PEP version as it depends on an `sgpr` package that is not part of this code.

### CODE REVIEW

File: code/run_reg_toy.py [hunk 1]
```diff
@@ -300,8 +260,8 @@ def plot_VFE_optimized(M, use_old_Z, shuffle):
     seed = 10
     shuffle = False
 
-    np.random.seed(seed)
-    plot_PEP_optimized(10, alpha, use_old_Z, shuffle)
+    # np.random.seed(seed)
+    # plot_PEP_optimized(10, alpha, use_old_Z, shuffle)
```
Comment (st--) [inline code/run_reg_toy.py]: Commented out so the script runs even though the `sgpr` package is not present.

File: code/run_reg_toy.py [hunk 2]
```diff
@@ -50,15 +49,10 @@ def figsize(scale, ratio=None):
...
 
-import scipy as scp
-# import sys
-# sys.path.append('/scratch/tdb40/sandbox/GPflow/gpflow')
-import gpflow as GPflow
+import gpflow
 import osgpr
-import sgpr
-import pdb
+# import sgpr
```
Comment (st--) [inline code/run_reg_toy.py]: Not provided

**Comment by thangbui** [comment]
Hi @st--, thanks for doing this. `sgpr` is [here](https://github.com/thangbui/streaming_sparse_gp/blob/master/code/sgpr.py). The `SGPR_PEP` class in there is similar to [`SGPR`](https://github.com/GPflow/GPflow/blob/0.4.0/gpflow/sgpr.py). Could you upgrade this as well :D

**Comment by st--** [comment]
@thangbui thanks for pointing it out, I had completely missed the presence of the sgpr.py file! I've now upgraded that as well and the run_reg_toy script now runs both VFE and PEP versions just fine:)

**Comment by thangbui** [comment]
Thanks @st--! This looks great to me. Works with gpflow 2.5. Would be great if you also modify the readme file as well: remove the line saying tested with gpflow 0.4.0 and add your name to the contributor list.

One thing though, I got this error when running run_cla_toy.py with the latest version of gpflow (2.6.1):

`TypeError: outer_factory.<locals>.inner_factory.<locals>.tf__variational_expectations() missing 1 required positional argument: 'Y'`

which happens on line 105 of `osvgpc.py`. This seems very strange. Do I need another argument for variational_expectation in the latest gpflow? I glanced at the repo but didn't see anything on this. Or perhaps this is a bug with gpflow 2.6?

**Comment by st--** [comment]
Yeah, unfortunately there was a breaking change in gpflow 2.6: https://github.com/GPflow/GPflow/pull/1919 - I'll add a workaround.

**Comment by st--** [comment]
@thangbui done that now. But I've not tested with gpflow 2.6, could you quickly run it to make sure it works for you?

File: code/osvgpc.py [hunk 3]
```diff
@@ -20,108 +18,113 @@ class OSVGPC(GPModel):
...
+            var_exp = self.likelihood.variational_expectations(fmean, fvar, Y)
+        else:
+            # breaking change https://github.com/GPflow/GPflow/pull/1919
+            var_exp = self.likelihood.variational_expectations(X, fmean, fvar, Y)
 
         # re-scale for minibatch size
-        scale = tf.cast(self.num_data, settings.dtypes.float_type) /\
-            tf.cast(tf.shape(self.X)[0], settings.dtypes.float_type)
+        if self.num_data is not None:
+            raise NotImplementedError("need to update code to ExternalDataTrainingLossMixin")
```
Comment (st--) [inline code/osvgpc.py:113]: @thangbui I had added this because this would require a bit more of a rewrite to allow for mini-batching (which unfortunately is a bit more manual in gpflow 2)...

File: code/run_cla_toy.py [hunk 4]
```diff
@@ -163,28 +161,27 @@ def run_vfe(no_batches, M, use_old_Z, iid):
...
-                                mu, Su, Kaa, Zopt, Zinit)
-            model.kern.variance = model.kern.variance.value
-            model.kern.lengthscales = model.kern.lengthscales.value
-            model.optimize(disp=1, maxiter=maxiter)
-        Zopt = model.Z.value
-        mu, Su = model.predict_f_full_cov(Zopt)
+            model = osvgpc.OSVGPC((Xi, yi), gpflow.kernels.RBF(lengthscales=np.ones(2)),
+                                  gpflow.likelihoods.Bernoulli(),
+                                  mu, Su, Kaa, Zopt, Zinit)
+            # TODO: what does this do: ???
```
Comment (st--) [inline code/run_cla_toy.py]: @thangbui was this supposed to keep the hyperparameters fixed or something?

Comment (thangbui) [reply code/run_cla_toy.py]: I vaguely recall that if I didn't do this, the kernels were not initialised correctly, but as the comment suggests, I don't know why I had it there. Everything seems to work fine so we should delete these lines.

**Comment by thangbui** [comment]
Perfect, now also works with gpflow 2.6. Thanks @st--!

Happy to merge if you don't have any pending changes.

File: code/run_cla_toy.py (hunk 4 above)
Comment (st--) [reply code/run_cla_toy.py]: Ok, removed the commented-out lines :)

**Comment by st--** [comment]
@thangbui I've removed the commented-out lines and pushed my changes, all good from my side!

**Comment by st--** [comment]
@thangbui I just realised the URL I added to my name in the README is broken; it's missing the `https://` at the start, could you quickly fix that directly? Otherwise I can open a new PR for that too

**Comment by thangbui** [comment]
No worries. Fixed.

**Comment by st--** [comment]
@thangbui thanks! I would recommend also turning the mention of your paper into an actual link to arxiv/proceedings:)

**Comment by thangbui** [comment]
thanks, updated that as well!
